"""
Briefing exporter
=================
Converts the markdown executive briefing into:
  - HTML  (always works, no dependencies)
  - DOCX  (if python-docx is installed)
  - PDF   (if reportlab is installed)

Each exporter is independent -- if a library isn't installed, that format is
gracefully unavailable and the others still work.
"""
import re
from datetime import datetime
from io import BytesIO
from typing import Tuple, Optional


# ---------------------------------------------------------------------------
# Markdown helpers (we only need a tiny subset)
# ---------------------------------------------------------------------------
_BOLD_RE = re.compile(r"\*\*(.+?)\*\*")


def _parse_markdown(md: str):
    """
    Yield (kind, text) tuples for a tiny subset of markdown:
      kind ∈ {"heading", "bullet", "numbered", "paragraph", "blank"}
    Bold (**...**) is preserved as a marker but stripped of asterisks.
    """
    for line in md.splitlines():
        s = line.strip()
        if not s:
            yield "blank", ""
            continue
        if s.startswith("**") and s.endswith("**") and len(s) > 4:
            yield "heading", s[2:-2]
            continue
        if s.startswith("- ") or s.startswith("• "):
            yield "bullet", s[2:].strip()
            continue
        m = re.match(r"^(\d+)\.\s+(.*)$", s)
        if m:
            yield "numbered", f"{m.group(1)}. {m.group(2)}"
            continue
        yield "paragraph", s


def _strip_bold(s: str) -> str:
    return _BOLD_RE.sub(r"\1", s)


# ===========================================================================
# HTML export -- always available
# ===========================================================================
def export_html(briefing_md: str, candidate_name: str = "") -> bytes:
    """Return a complete styled HTML document as bytes."""
    body_parts = []
    for kind, text in _parse_markdown(briefing_md):
        if kind == "heading":
            body_parts.append(f"<h2>{_strip_bold(text)}</h2>")
        elif kind == "bullet":
            body_parts.append(f"<li>{_render_inline(text)}</li>")
        elif kind == "numbered":
            body_parts.append(f"<li>{_render_inline(text)}</li>")
        elif kind == "paragraph":
            body_parts.append(f"<p>{_render_inline(text)}</p>")
        elif kind == "blank":
            body_parts.append("")

    # Wrap consecutive bullets in <ul> -- simple post-pass
    html_body = _wrap_lists("\n".join(body_parts))

    full = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>AI Initiatives Executive Briefing</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; max-width: 760px; margin: 40px auto; padding: 0 24px; color: #222; line-height: 1.55; }}
  .brand {{ display:inline-block; background:#003D6E; color:white; padding:6px 12px; border-radius:3px; font-weight:700; font-size:13px; letter-spacing:0.5px; }}
  .meta  {{ color:#666; font-size:13px; margin: 8px 0 24px 0; }}
  h1 {{ color:#003D6E; border-bottom: 2px solid #003D6E; padding-bottom: 8px; margin-top: 24px; }}
  h2 {{ color:#003D6E; margin-top: 28px; font-size: 18px; }}
  ul, ol {{ padding-left: 22px; }}
  li {{ margin-bottom: 6px; }}
  p {{ margin: 8px 0; }}
  strong {{ color:#003D6E; }}
  .footer {{ margin-top: 60px; padding-top: 16px; border-top: 1px solid #ddd; color:#999; font-size:11px; text-align:center; }}
</style>
</head>
<body>
  <div class="brand">MORGAN STANLEY</div>
  <h1>AI Initiatives — Executive Briefing</h1>
  <div class="meta">
    Technology COO · Transformation Team<br>
    Generated {datetime.now().strftime('%B %d, %Y at %H:%M')}
    {f"· Prepared by {candidate_name}" if candidate_name and candidate_name != "[Your Name]" else ""}
  </div>
  {html_body}
  <div class="footer">
    Generated by the AI Initiatives Agentic Reporting Platform.<br>
    All initiative data shown is simulated for prototype demonstration.
  </div>
</body>
</html>"""
    return full.encode("utf-8")


def _render_inline(s: str) -> str:
    """Convert inline **bold** to <strong>."""
    return _BOLD_RE.sub(r"<strong>\1</strong>", s)


def _wrap_lists(html: str) -> str:
    """Wrap runs of <li> in <ul>."""
    lines = html.split("\n")
    out = []
    in_list = False
    for ln in lines:
        if ln.startswith("<li>"):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(ln)
        else:
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(ln)
    if in_list:
        out.append("</ul>")
    return "\n".join(out)


# ===========================================================================
# DOCX export -- requires python-docx
# ===========================================================================
def docx_available() -> bool:
    try:
        import docx  # noqa
        return True
    except ImportError:
        return False


def export_docx(briefing_md: str, candidate_name: str = "") -> Optional[bytes]:
    """Return docx bytes, or None if python-docx is not installed."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        return None

    doc = Document()

    # Header / branding
    brand = doc.add_paragraph()
    brand_run = brand.add_run("MORGAN STANLEY")
    brand_run.bold = True
    brand_run.font.size = Pt(11)
    brand_run.font.color.rgb = RGBColor(0x00, 0x3D, 0x6E)

    title = doc.add_heading("AI Initiatives — Executive Briefing", level=0)
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x00, 0x3D, 0x6E)

    meta = doc.add_paragraph()
    meta_run = meta.add_run(
        f"Technology COO · Transformation Team\n"
        f"Generated {datetime.now().strftime('%B %d, %Y at %H:%M')}"
    )
    meta_run.font.size = Pt(10)
    meta_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
    if candidate_name and candidate_name != "[Your Name]":
        meta.add_run(f" · Prepared by {candidate_name}").font.size = Pt(10)

    doc.add_paragraph()  # spacer

    # Body
    for kind, text in _parse_markdown(briefing_md):
        if kind == "heading":
            h = doc.add_heading(_strip_bold(text), level=2)
            for run in h.runs:
                run.font.color.rgb = RGBColor(0x00, 0x3D, 0x6E)
        elif kind == "bullet":
            doc.add_paragraph(_strip_bold(text), style="List Bullet")
        elif kind == "numbered":
            # Strip the leading "1. " so Word can do its own numbering
            stripped = re.sub(r"^\d+\.\s+", "", text)
            doc.add_paragraph(_strip_bold(stripped), style="List Number")
        elif kind == "paragraph":
            p = doc.add_paragraph()
            _add_runs_with_bold(p, text)

    # Footer
    doc.add_paragraph()
    foot = doc.add_paragraph()
    foot_run = foot.add_run(
        "Generated by the AI Initiatives Agentic Reporting Platform. "
        "All initiative data shown is simulated for prototype demonstration."
    )
    foot_run.font.size = Pt(8)
    foot_run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
    foot_run.italic = True

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _add_runs_with_bold(paragraph, text: str):
    """Add text to a python-docx paragraph, honoring **bold** markers."""
    pos = 0
    for m in _BOLD_RE.finditer(text):
        if m.start() > pos:
            paragraph.add_run(text[pos:m.start()])
        bold_run = paragraph.add_run(m.group(1))
        bold_run.bold = True
        pos = m.end()
    if pos < len(text):
        paragraph.add_run(text[pos:])


# ===========================================================================
# PDF export -- requires reportlab
# ===========================================================================
def pdf_available() -> bool:
    try:
        import reportlab  # noqa
        return True
    except ImportError:
        return False


def export_pdf(briefing_md: str, candidate_name: str = "") -> Optional[bytes]:
    """Return PDF bytes, or None if reportlab is not installed."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
        from reportlab.lib.enums import TA_LEFT
    except ImportError:
        return None

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=0.9 * inch, rightMargin=0.9 * inch,
        topMargin=0.9 * inch, bottomMargin=0.8 * inch,
        title="AI Initiatives Executive Briefing",
    )

    styles = getSampleStyleSheet()
    ms_blue = HexColor("#003D6E")

    brand_style = ParagraphStyle(
        "Brand", parent=styles["Normal"],
        textColor="white", backColor=ms_blue,
        fontName="Helvetica-Bold", fontSize=10, leading=14,
        leftIndent=4, rightIndent=4, spaceBefore=2, spaceAfter=2,
    )
    title_style = ParagraphStyle(
        "Title2", parent=styles["Title"],
        textColor=ms_blue, fontSize=20, leading=24, alignment=TA_LEFT,
        spaceBefore=8, spaceAfter=4,
    )
    meta_style = ParagraphStyle(
        "Meta", parent=styles["Normal"],
        textColor=HexColor("#666666"), fontSize=9, leading=12, spaceAfter=18,
    )
    h2_style = ParagraphStyle(
        "H2", parent=styles["Heading2"],
        textColor=ms_blue, fontSize=13, spaceBefore=14, spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontSize=10.5, leading=15, spaceAfter=6,
    )
    bullet_style = ParagraphStyle(
        "Bullet", parent=body_style, leftIndent=14, bulletIndent=4,
    )
    foot_style = ParagraphStyle(
        "Foot", parent=styles["Normal"],
        textColor=HexColor("#999999"), fontSize=8, alignment=1, spaceBefore=24,
    )

    story = []
    story.append(Paragraph("&nbsp;MORGAN STANLEY&nbsp;", brand_style))
    story.append(Spacer(1, 8))
    story.append(Paragraph("AI Initiatives — Executive Briefing", title_style))

    meta_text = (
        f"Technology COO · Transformation Team<br/>"
        f"Generated {datetime.now().strftime('%B %d, %Y at %H:%M')}"
    )
    if candidate_name and candidate_name != "[Your Name]":
        meta_text += f" · Prepared by {candidate_name}"
    story.append(Paragraph(meta_text, meta_style))

    # Body -- collapse runs of bullets into ListFlowable
    pending_bullets = []

    def flush_bullets():
        if pending_bullets:
            items = [ListItem(Paragraph(_md_to_rl(t), bullet_style)) for t in pending_bullets]
            story.append(ListFlowable(items, bulletType="bullet", leftIndent=18))
            story.append(Spacer(1, 4))
            pending_bullets.clear()

    for kind, text in _parse_markdown(briefing_md):
        if kind in ("heading", "paragraph", "numbered", "blank"):
            flush_bullets()
        if kind == "heading":
            story.append(Paragraph(_md_to_rl(_strip_bold(text)), h2_style))
        elif kind == "bullet":
            pending_bullets.append(text)
        elif kind == "numbered":
            story.append(Paragraph(_md_to_rl(text), body_style))
        elif kind == "paragraph":
            story.append(Paragraph(_md_to_rl(text), body_style))
    flush_bullets()

    story.append(Paragraph(
        "Generated by the AI Initiatives Agentic Reporting Platform.<br/>"
        "All initiative data shown is simulated for prototype demonstration.",
        foot_style,
    ))

    doc.build(story)
    return buf.getvalue()


def _md_to_rl(s: str) -> str:
    """Convert **bold** to ReportLab's <b>...</b> tags. HTML-escape <,>,& first."""
    s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return _BOLD_RE.sub(r"<b>\1</b>", s)


# ===========================================================================
# Convenience: get all available formats with mime types
# ===========================================================================
def available_formats() -> dict:
    """Returns dict of {format_name: (mime_type, extension, available)}"""
    return {
        "html": ("text/html", "html", True),
        "docx": ("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx", docx_available()),
        "pdf":  ("application/pdf", "pdf", pdf_available()),
    }
